lexik_jwt_authentication:
    private_key_path: "%jwt_private_key_path%"
    public_key_path:  "%jwt_public_key_path%"
    pass_phrase:      "%jwt_key_pass_phrase%"
    token_ttl:        "%jwt_token_ttl%"
    user_identity_field: "username"
    encoder:
        service: app.jwt_authentication.encoder
    token_extractors:
        authorization_header:
            prefix:   "%jwt_token_authorization_header_prefix%"