# Vich Uploader Configuration
vich_uploader:
    db_driver: orm
    storage:   file_system
    mappings:
        private_media_uploader:
            uri_prefix:         /private
            upload_destination: '%kernel.project_dir%/private'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer: 'EasyApiBundle\Services\MediaUploader\MediaUploaderFileNamer'
            directory_namer: 'EasyApiBundle\Services\MediaUploader\MediaUploaderDirectoryNamer'
        public_media_uploader:
            uri_prefix:         '%router.request_context.scheme%://%router.request_context.host%'
            upload_destination: '%kernel.project_dir%/public'
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer: 'EasyApiBundle\Services\MediaUploader\MediaUploaderFileNamer'
            directory_namer: 'EasyApiBundle\Services\MediaUploader\MediaUploaderDirectoryNamer'
