services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EasyApiBundle\Serializer\:
    resource: '../../Serializer'

  EasyApiBundle\Services\MediaUploader\:
    public: true
    resource: '../../Services/MediaUploader'

  EasyApiBundle\EventListener\FileManagerListener:
    public: true
    tags:
      - { name: doctrine.event_listener, event: postLoad }

  EasyApiBundle\Services\ApiDoc\GetFormParameterRouteDescriber:
    tags:
      - 'nelmio_api_doc.route_describer'

  EasyApiBundle\Services\ApiDoc\GetFormFilterParameterRouteDescriber:
    tags:
      - 'nelmio_api_doc.route_describer'

  EasyApiBundle\Services\ListFilter:
    public: true
    arguments: ['@service_container', '@security.token_storage']

  EasyApiBundle\Services\EntitySerializer:
    public: true

  app.jwt_authentication.jws_provider:
    class: EasyApiBundle\Services\JWS\JWSProvider
    public: true
    arguments:
      - '@lexik_jwt_authentication.key_loader'
      - '%lexik_jwt_authentication.encoder.crypto_engine%'
      - '%lexik_jwt_authentication.encoder.signature_algorithm%'
      - '%lexik_jwt_authentication.token_ttl%'
      - '%jwt_token_authorization_header_prefix%'
      - '@security.token_storage'
      - '@doctrine.orm.entity_manager'
      - '%easy_api.user_class%'
      - '%lexik_jwt_authentication.user_identity_field%'

  Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\JWSProviderInterface:
    alias: app.jwt_authentication.jws_provider
    public: false

  app.jwt_authentication.encoder:
    autowire: false
    autoconfigure: false
    public: false
    parent: 'lexik_jwt_authentication.encoder.default'
    arguments: ['@app.jwt_authentication.jws_provider']

  Lexik\Bundle\JWTAuthenticationBundle\Encoder\JWTEncoderInterface:
    alias: app.jwt_authentication.encoder
    public: false

  # JWT JWT_AUTHENTICATED - Token used
  app.event.jwt_authenticated_listener:
    class: EasyApiBundle\EventListener\JWTAuthenticatedListener
    arguments: ['@doctrine.orm.entity_manager', '@router.request_context', '@request_stack', '%lexik_jwt_authentication.token_ttl%', '@service_container', '@security.encoder_factory']
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_authenticated, method: onJWTAuthenticated }

  # JWT AUTHENTICATION_FAILURE
  app.event.authentication_failure_listener:
    class: EasyApiBundle\EventListener\JWTFailureListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

  # JWT JWT_INVALID
  app.event.jwt_invalid_listener:
    class: EasyApiBundle\EventListener\JWTFailureListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }

  # JWT JWT_NOT_FOUND
  app.event.jwt_not_found_listener:
    class: EasyApiBundle\EventListener\JWTFailureListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }

  # JWT JWT_EXPIRED
  app.event.jwt_expired_listener:
    class: EasyApiBundle\EventListener\JWTFailureListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }

  app.user_provider:
    class: EasyApiBundle\Services\User\UsernameEmailProvider
    public: true
    arguments: ['@doctrine.orm.entity_manager', '%easy_api.user_class%']

  # Form errors serializer
  EasyApiBundle\Form\Serializer\FormErrorsSerializer:
    arguments: ['@logger']
    public: true
#
##  # Anonymous data manager
##  app.anonymous_data_manager:
##    class: EasyApiBundle\Util\AnonymousDataManager
##    arguments: ['@doctrine.orm.entity_manager', '@lexik_jwt_authentication.encoder']
#
  app.api_exception_subscriber:
    class: EasyApiBundle\EventListener\ApiExceptionSubscriber
    arguments: ['@logger', '%kernel.environment%']
    tags:
      - { name: kernel.event_subscriber }

  EasyApiBundle\Services\User\Tracking:
    public: true
    arguments: ['@service_container', '@security.token_storage']

  EasyApiBundle\Controller\User\:
    resource: '../../Controller/User'
    public: true
    tags: [ 'controller.service_arguments']